export const productFilters = ['All', 'Home Automation', 'Security & Access', 'Audio & Video', 'Community Solutions', 'Sports & Infrastructure', 'Function Hall Solutions'] as const;
export type ProductCategory = Exclude<typeof productFilters[number], 'All'>;
export type Product = {name: string; categories: ProductCategory[]; image: string; alt: string; description: string; points: string[]};
const security: ProductCategory = 'Security & Access';
const automation: ProductCategory = 'Home Automation';
const av: ProductCategory = 'Audio & Video';
const community: ProductCategory = 'Community Solutions';
const sports: ProductCategory = 'Sports & Infrastructure';
const hall: ProductCategory = 'Function Hall Solutions';
const product = (slug: string, name: string, categories: ProductCategory[], description: string, alt: string, points: string[]): Product => ({name, categories, image: `/images/products/${slug}.jpg`, description, alt, points});

export const products: Product[] = [
 product('home-automation', 'Home Automation', [automation], 'Bring everyday home controls together.', 'Home automation control system', ["Connect compatible lighting, curtains and climate controls.", "Create routines for mornings, evenings and time away.", "Choose controls that suit your household."]),
 product('digital-door-lock', 'Digital Door Locks', [security], 'Convenient digital access for your entrance.', 'Digital door lock on an entrance door', ["Keyless entry options vary by lock model.", "Choose a lock suited to your door material and thickness.", "Plan access for family members and visitors."]),
 product('home-theater', 'Home Theater', [av], 'A dedicated cinema experience at home.', 'Home theater screen and seating', ["Bring projection, sound and seating into one space.", "Plan speaker positions around the room layout.", "Include acoustic treatment and lighting in the design."]),
 product('cctv', 'CCTV', [security, hall], 'Surveillance for homes and shared spaces.', 'CCTV surveillance camera', ["Monitor entrances, parking and shared areas.", "Choose camera positions for the coverage you need.", "Recording and remote viewing depend on the selected setup."]),
 product('intercom-systems', 'Intercom Systems', [security, hall], 'Simple communication across your property.', 'Intercom communication system', ["Speak between rooms, entrances or reception areas.", "Useful for villas, apartments and event venues.", "Choose wired or compatible network-based options."]),
 product('video-door-phone', 'Video Door Phones', [security], 'See and speak with visitors at your door.', 'Video door phone monitor and entrance unit', ["See and speak with visitors from an indoor monitor.", "Position the entrance unit for a clear visitor view.", "Door-release integration depends on compatible hardware."]),
 product('access-control', 'Access Control Systems', [security, hall], 'Manage entry to your property.', 'Access control reader at an entrance', ["Control access to selected doors and entry points.", "Card, PIN or biometric options depend on the reader.", "Plan access permissions for different users."]),
 product('remote-gates', 'Remote Gates', [security, hall], 'Convenient automated gate access.', 'Remote operated entrance gate', ["Automate compatible sliding or swing gates.", "Select a motor suited to gate size and weight.", "Include safety sensing and manual access in the plan."]),
 product('boom-barriers', 'Boom Barriers', [security, hall], 'Manage vehicle entry and exit.', 'Vehicle access boom barrier', ["Manage vehicle movement at entry and exit lanes.", "Suitable for communities, parking areas and venues.", "Select controls to match the access workflow."]),
 product('security-sensors', 'Security Sensors', [security], 'Add monitoring to key areas of your home.', 'Home security sensor', ["Detect motion or door and window activity.", "Place sensors around the areas you want to monitor.", "Alerts and automation require compatible connected devices."]),
 product('solar-fencing', 'Solar Fencing', [security, hall], 'Solar-powered perimeter security.', 'Solar fencing along a property boundary', ["Add an electric deterrent along a property boundary.", "Pair fencing with a solar-powered energizer setup.", "Plan professional installation, signage and maintenance."]),
 product('motorized-curtains', 'Motorized Curtains', [automation], 'Open and close curtains with ease.', 'Motorized curtains on a residential window', ["Move curtains along a motorized track.", "Choose track lengths to suit the window opening.", "Remote and scheduled control depend on the system."]),
 product('motorized-blinds', 'Motorized Blinds', [automation], 'Convenient control of light and privacy.', 'Motorized window blinds', ["Adjust window coverage for daylight and privacy.", "Select blind fabric and dimensions for each room.", "Integrate compatible motors with room controls."]),
 product('transparent-elevation-motorized-shutters', 'Transparent Elevation Motorized Shutters', [automation], 'Motorized transparent shutters for building elevations.', 'Transparent motorized elevation shutters', ["Maintain visibility through a transparent shutter.", "Motorized operation for suitable building openings.", "Plan guide rails, housing and access for servicing."]),
 product('pa-sound-systems', 'P.A. Sound Systems', [av, hall], 'Sound systems for announcements and events.', 'Public address sound system speakers', ["Distribute announcements and event audio.", "Choose speaker placement for the room and audience.", "Match microphones and mixers to the intended use."]),
 product('projectors', 'Projectors', [av, hall], 'Large-format visuals for films and presentations.', 'Presentation and home cinema projector', ["Show films, lessons or presentations on a large surface.", "Match brightness and placement to the room.", "Check connections for your preferred media sources."]),
 product('projection-screens', 'Projection Screens', [av, hall], 'A dedicated surface for projected visuals.', 'Projection screen for presentations and cinema', ["Provide a dedicated surface for projected content.", "Choose screen dimensions for the viewing distance.", "Fixed and retractable options suit different spaces."]),
 product('led-display-screens', 'LED Display Screens', [av, hall], 'Display content across shared and event spaces.', 'LED display screen', ["Present video and event content on a large display.", "Choose pixel spacing for the viewing distance.", "Indoor and outdoor installations need different specifications."]),
 product('podiums-with-speakers', 'Podiums with Speakers', [av], 'Presentation podiums with integrated speakers.', 'Presentation podium with speakers', ["Combine a presentation surface with audio equipment.", "Suitable for meetings, classrooms and event spaces.", "Check microphone connections and power requirements."]),
 product('artificial-lawn', 'Artificial Lawn', [community], 'Green finishes for landscaped spaces.', 'Artificial lawn in a landscaped area', ["Create a green finish for gardens and terraces.", "Avoid the mowing needed by natural grass.", "Plan drainage, cleaning and a suitable base."]),
 product('wooden-flooring', 'Wooden Flooring', [community], 'Warm wood finishes for interior spaces.', 'Wooden interior flooring', ["Add wood texture to living and shared spaces.", "Choose a finish suited to the room and usage.", "Check subfloor condition and moisture before installation."]),
 product('swimming-pools', 'Swimming Pools', [community], 'Pool solutions for villas and communities.', 'Residential community swimming pool', ["Plan a pool for a villa or community space.", "Coordinate filtration, circulation and pool lighting.", "Allow for routine cleaning and water maintenance."]),
 product('gym-equipment', 'Gym Equipment', [community], 'Equip dedicated fitness spaces.', 'Gym fitness equipment', ["Combine cardio and strength-training equipment.", "Select equipment around available floor space.", "Leave room for safe movement and servicing."]),
 product('gym-flooring', 'Gym Flooring', [community], 'Flooring for workout and fitness areas.', 'Flooring in a gym workout area', ["Define workout zones with suitable flooring.", "Choose material thickness for the intended activities.", "Plan for cleaning, joints and equipment placement."]),
 product('running-track-epdm', 'Running Track EPDM', [sports], 'EPDM surfacing for running tracks.', 'EPDM running track surface', ["Create a dedicated running surface with lane markings.", "Choose colours and layout for the available area.", "A prepared base and drainage support the installation."]),
 product('wooden-shuttle-court', 'Wooden Shuttle Court', [sports], 'Wooden court flooring for badminton.', 'Wooden badminton court', ["Provide a wooden playing surface for badminton.", "Coordinate court markings, net positions and clearances.", "Plan indoor moisture control and floor maintenance."]),
 product('basketball-court', 'Basketball Court', [sports], 'Dedicated court spaces for basketball.', 'Basketball court surface and markings', ["Create a defined playing area with court markings.", "Coordinate hoop positions and surrounding clear space.", "Choose surfacing for indoor or outdoor use."]),
 product('volleyball-court', 'Volleyball Court', [sports], 'Dedicated court spaces for volleyball.', 'Volleyball court with net', ["Set out a volleyball playing area and boundary lines.", "Include net posts and appropriate surrounding clearance.", "Choose a surface for the intended location and usage."]),
 product('multi-sport-turf', 'Cricket / Volleyball / Football Turf', [sports], 'Turf solutions for outdoor sports spaces.', 'Multi-sport turf playing surface', ["Use a shared area for sports and practice sessions.", "Plan markings and equipment for the selected games.", "Include drainage and perimeter netting where needed."]),
 product('astro-turf', 'Astro Turf', [sports], 'Artificial turf for sports and recreation.', 'Astro turf sports surface', ["Provide synthetic grass for recreation and sport.", "Choose pile and infill to suit the activity.", "Regular brushing and cleaning help maintain the surface."]),
 product('indoor-games', 'Indoor Games', [sports], 'Create shared spaces for indoor recreation.', 'Indoor games equipment', ["Create recreation areas for residents or students.", "Options include table tennis and carrom setups.", "Allow space around tables for comfortable play."]),
 product('pp-sports-tiles', 'PP Tiles for Sports', [sports], 'Polypropylene tiles for sports surfaces.', 'Interlocking polypropylene sports tiles', ["Use interlocking tiles to form a sports surface.", "Combine colours to define courts and activity zones.", "Check base preparation and suitability for the sport."]),
 product('synthetic-sports-flooring-paint', 'Synthetic Paint for Sports Flooring', [sports], 'Surface finishes for sports flooring.', 'Synthetic painted sports flooring', ["Finish prepared sports surfaces with coloured coatings.", "Add contrasting court lines and activity markings.", "Select the coating for the base and exposure conditions."]),
 product('function-hall-chairs', 'Function Hall Chairs', [hall], 'Seating for gatherings and celebrations.', 'Function hall event chairs', ["Plan seating for meetings, celebrations and gatherings.", "Choose upholstery and frames to suit the venue.", "Consider storage, cleaning and seating arrangements."]),
 product('premium-sofas-lounge-seating', 'Premium Sofas & Lounge Seating', [hall], 'Comfortable seating for event lounge spaces.', 'Premium sofa and event lounge seating', ["Create relaxed seating areas for guests.", "Coordinate sofa sizes and fabrics with the venue.", "Leave comfortable circulation space around seating."]),
];
