'use client';
import {useEffect,useRef,useState} from 'react';
import Image from 'next/image';
import {business,footerColumns} from '@/lib/experience-content';
import {Facebook,Instagram,Youtube,Menu,X} from 'lucide-react';
const navLinks:{label:string;href?:string}[]=[{label:'Products',href:'/products'},{label:'Solutions',href:'/#solutions'},{label:'Projects',href:'/#projects'}];
export function Header(){const [open,setOpen]=useState(false);return <><a className="skip-link" href="#main-content">Skip to content</a><header className="new-header locked-header"><a href="/" className="wordmark" aria-label="ABHEE Smart Home Systems home"><Image className="header-logo" src="/images/abhee-logo.png" alt="ABHEE Smart Home Systems" width={1735} height={453} unoptimized sizes="(max-width: 800px) 170px, 240px" priority/></a><nav className={open?'header-nav open':'header-nav'} aria-label="Main navigation">{navLinks.map(x=>x.href?<a key={x.label} href={x.href} onClick={()=>setOpen(false)}>{x.label}</a>:<span className="header-nav-inert" key={x.label}>{x.label}</span>)}</nav><div className="header-actions"><a className="cta" href={`https://wa.me/${business.whatsapp}?text=${encodeURIComponent("Hi ABHEE, I would like to book a site visit.")}`} target="_blank" rel="noopener noreferrer">Book a Visit</a><button className="menu-toggle" aria-expanded={open} aria-label={open?'Close menu':'Open menu'} onClick={()=>setOpen(!open)} onKeyDown={e=>{if(e.key==='Escape')setOpen(false)}}>{open?<X size={22} aria-hidden="true"/>:<Menu size={22} aria-hidden="true"/>}</button></div></header></>}
const socialIcons=[{name:'Facebook',Icon:Facebook},{name:'Instagram',Icon:Instagram},{name:'YouTube',Icon:Youtube}];
export function Footer(){return <footer className="new-footer footer-five"><div className="footer-five-grid">
<div className="footer-col"><span>Category</span>{footerColumns.category.map(x=><span className="footer-static" key={x}>{x}</span>)}</div>
<div className="footer-col"><span>Info</span>{footerColumns.info.map(x=>{if(x==='Contact Us')return <button className="footer-link-btn" key={x} onClick={()=>window.dispatchEvent(new Event('abhee-contact'))}>{x}</button>;if(x==='About Us')return <a key={x} href="/#why-abhee">{x}</a>;return <span className="footer-static" key={x}>{x}</span>})}</div>
<div className="footer-col"><span>Support</span>{footerColumns.support.map(x=>x==='Terms of Use'?<a key={x} href="/terms-and-conditions">{x}</a>:<span className="footer-static" key={x}>{x}</span>)}</div>
<div className="footer-col"><span>Social</span><div className="footer-social">{socialIcons.map(({name,Icon})=>{const social=business.social.find(s=>s.name===name);return social?<a key={name} href={social.url} target="_blank" rel="noreferrer" aria-label={name}><Icon size={16}/></a>:<span className="footer-social-icon" key={name} aria-label={`${name} — coming soon`}><Icon size={16}/></span>})}</div></div>
<div className="footer-col footer-subscribe"><span>Subscribe</span><p>Subscribe to our weekly newsletter and receive exclusive offers on products you love!</p><form className="footer-subscribe-form" onSubmit={e=>e.preventDefault()}><input type="email" placeholder="Email address" aria-label="Email address" required/><button type="submit">Submit</button></form></div>
</div><div className="footer-bottom"><span>© {new Date().getFullYear()} ABHEE Smart Home Systems</span><a href="/privacy-policy">Privacy Policy</a><a href="/terms-and-conditions">Terms & Conditions</a><a href="#main-content">Back to top ↑</a></div></footer>}
export function ContactLayer(){const dialog=useRef<HTMLDialogElement>(null);const [whatsapp,setWhatsapp]=useState(false);useEffect(()=>{const open=()=>{setWhatsapp(false);dialog.current?.showModal()};window.addEventListener('abhee-contact',open);return()=>window.removeEventListener('abhee-contact',open)},[]);return <><button className="whatsapp" aria-label="Talk to ABHEE on WhatsApp" onClick={()=>{if(business.whatsapp)window.open(`https://wa.me/${business.whatsapp}`,'_blank','noopener,noreferrer');else{setWhatsapp(true);dialog.current?.showModal()}}}><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" aria-hidden="true"><path d="M20 11.5a8 8 0 0 1-11.7 7.1L4 20l1.4-4.3A8 8 0 1 1 20 11.5Z"/><path d="M8 7c0 5 4 9 9 9l-1-3-2 1-4-4 1-2-3-1Z"/></svg></button><dialog ref={dialog} className="contact-dialog" aria-labelledby="contact-heading" onClick={e=>{if(e.target===e.currentTarget)dialog.current?.close()}}><button className="dialog-close" aria-label="Close contact dialog" onClick={()=>dialog.current?.close()}>✕</button><p className="eyebrow">LET’S START WITH YOUR HOME</p><h2 id="contact-heading">Make room<br/>for possibility.</h2><p>{whatsapp?'WhatsApp contact details will be added soon. You can reach ABHEE by email.':'Tell us about your home, your city, and a convenient time for a site visit.'}</p><a className="cta" href={`mailto:${business.email}?subject=${encodeURIComponent('ABHEE site visit enquiry')}`}>Email ABHEE <span>↗</span></a><p className="contact-note">Your email app will open. Visit timing is confirmed directly with ABHEE.</p></dialog></>}
