'use client';
import {useEffect,useRef,useState} from 'react';
import type {ExperienceImage} from '@/lib/experience-content';
import {ImagePlaceholder,SectionHeading} from './Primitives';
export function ScrollStory({id,eyebrow,title,copy,states,media,dark=false,security=false}:{id:string;eyebrow:string;title:string;copy?:string;states:string[];media:ExperienceImage[];dark?:boolean;security?:boolean}){
 const root=useRef<HTMLElement>(null);const [active,setActive]=useState(0);
 useEffect(()=>{const node=root.current;if(!node)return;const reduced=window.matchMedia('(prefers-reduced-motion: reduce)');let ticking=false;const update=()=>{const r=node.getBoundingClientRect();const distance=Math.max(1,r.height-window.innerHeight);setActive(Math.min(states.length-1,Math.max(0,Math.floor((-r.top/distance)*states.length))));ticking=false};const onScroll=()=>{if(!ticking&&!reduced.matches){ticking=true;requestAnimationFrame(update)}};window.addEventListener('scroll',onScroll,{passive:true});window.addEventListener('resize',onScroll);update();return()=>{window.removeEventListener('scroll',onScroll);window.removeEventListener('resize',onScroll)}},[states.length]);
 const select=(i:number)=>{setActive(i);if(!window.matchMedia('(prefers-reduced-motion: reduce)').matches&&root.current){const r=root.current.getBoundingClientRect();window.scrollTo({top:window.scrollY+r.top+(r.height-window.innerHeight)*(i+.15)/states.length,behavior:'smooth'})}};
 return <section ref={root} id={id} className={`scroll-story ${dark?'dark':''} ${security?'security-story':''}`} style={{'--steps':states.length} as React.CSSProperties}><div className="story-pinned"><div className="story-intro"><SectionHeading eyebrow={eyebrow} copy={copy}>{title}</SectionHeading><span className="story-counter">0{active+1}<span> / 0{states.length}</span></span></div><div className="story-stage">{media.map((image,i)=><div key={image.src} className={`story-frame ${active===i?'active':''}`} aria-hidden={active!==i}><ImagePlaceholder image={image}/></div>)}<div className="story-state"><span className="eyebrow">{security?['SMART LOCK','CAMERA','VIDEO DOOR PHONE','GATE AUTOMATION'][active]:'THE ABHEE EXPERIENCE'}</span><p key={active}>{states[active]}</p></div></div><div className="story-tabs" aria-label={`${eyebrow} scenes`}>{states.map((state,i)=><button key={state} aria-pressed={active===i} onClick={()=>select(i)}><span className="tab-line"/><span>{security?['Smart lock','Camera','Video door phone','Gate automation'][i]:state}</span></button>)}</div></div></section>
}
